In [1]:
import numpy as np
import os

In [22]:
S0 = 40.0              # spot stock price
K = 40.0               # strike
T = 0.5                # time to maturity (6months)
r = 0.1                 # risk free rate 
sig = 0.1               # diffusion coefficient or volatility
N = 2                   # number of periods or number of time steps  
payoff = "call"          # payoff 

In [23]:
dT = float(T) / N                             # Delta t
u = np.exp(sig * np.sqrt(dT))                 # up factor
d = 1.0 / u                                   # down factor 

In [24]:
u

1.0512710963760241

In [25]:
d

0.9512294245007139

In [26]:
a = np.exp(r * dT)    # risk free compound return
p = (a - d)/ (u - d)  # risk neutral up probability
q = 1.0 - p           # risk neutral down probability
p

0.7405483598480218

In [27]:
S = np.zeros((N + 1, N + 1))
S[0, 0] = S0
z = 1
for t in range(1, N + 1):
    for i in range(z):
        S[i, t] = S[i, t-1] * u
        S[i+1, t] = S[i, t-1] * d
    z += 1

In [28]:
S

array([[40.        , 42.05084386, 44.20683672],
       [ 0.        , 38.04917698, 40.        ],
       [ 0.        ,  0.        , 36.19349672]])

In [29]:
S_T = S[:,-1]
V = np.zeros((N + 1, N + 1))
if payoff =="call":
    V[:,-1] = np.maximum(S_T-K, 0.0)
elif payoff =="put":
    V[:,-1] = np.maximum(K-S_T, 0.0)
V

array([[0.        , 0.        , 4.20683672],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ]])

In [30]:
# for European Option
for j in range(N-1, -1, -1):
    for i in range(j+1):
        V[i,j] = np.exp(-r*dT) * (p * V[i,j + 1] + q * V[i + 1,j + 1])
V

array([[2.19456163, 3.03844737, 4.20683672],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ]])

In [31]:
print('The European ' + payoff, str( V[0,0]))

The European call 2.19456162714245
